title: Visualizing Crashes in Philadelphia
logo: /assets/img/crashes.png
description: Analyzing crashes in Philadelphia districts
show_downloads: false
repository: MUSA-550-Fall-2021/github-pages-single-page-starter
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
